name: example
description: An example Flutter project using Drawer Manager.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: 1.0.4
  font_awesome_flutter: 9.2.0
  webview_flutter: 3.0.1

  drawer_manager:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/the-mac-avatar.jpeg

